#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
# Using build pattern: R
# autospec version: v5
# autospec commit: c02b2fe
#
Name     : R-maxLik
Version  : 1.5.2.1
Release  : 58
URL      : https://cran.r-project.org/src/contrib/maxLik_1.5-2.1.tar.gz
Source0  : https://cran.r-project.org/src/contrib/maxLik_1.5-2.1.tar.gz
Summary  : Maximum Likelihood Estimation and Related Tools
Group    : Development/Tools
License  : GPL-2.0+
Requires: R-generics
Requires: R-miscTools
Requires: R-sandwich
BuildRequires : R-generics
BuildRequires : R-miscTools
BuildRequires : R-sandwich
BuildRequires : buildreq-R
# Suppress stripping binaries
%define __strip /bin/true
%define debug_package %{nil}

%description
optimization, and related tools.  It includes a unified way to call
   different optimizers, and classes and methods to handle the results from
   the Maximum Likelihood viewpoint.  It also includes a number of convenience
   tools for testing and developing your own models.

%prep
%setup -q -n maxLik
pushd ..
cp -a maxLik buildavx2
popd
pushd ..
cp -a maxLik buildavx512
popd

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1711314842

%install
export SOURCE_DATE_EPOCH=1711314842
rm -rf %{buildroot}
LANG=C.UTF-8
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -O3 -flto -fno-semantic-interposition "
FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -flto -fno-semantic-interposition "
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -flto -fno-semantic-interposition "
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -O3 -flto -fno-semantic-interposition "
AR=gcc-ar
RANLIB=gcc-ranlib
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS  -Wl,-z -Wl,relro"
mkdir -p %{buildroot}/usr/lib64/R/library
mkdir -p %{buildroot}-v3/usr/lib64/R/library
mkdir -p %{buildroot}-v4/usr/lib64/R/library
mkdir -p %{buildroot}-va/usr/lib64/R/library

mkdir -p ~/.R
echo "CFLAGS = $CFLAGS -march=x86-64-v3 -ftree-vectorize -mno-vzeroupper" > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -march=x86-64-v3 -ftree-vectorize -mno-vzeroupper " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -march=x86-64-v3 -ftree-vectorize -mno-vzeroupper " >> ~/.R/Makevars
R CMD INSTALL  --install-tests --use-LTO --built-timestamp=${SOURCE_DATE_EPOCH} --data-compress=none --compress=none --build  -l %{buildroot}-v3/usr/lib64/R/library .
echo "CFLAGS = $CFLAGS -march=x86-64-v4 -mprefer-vector-width=512 -ftree-vectorize  -mno-vzeroupper " > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -march=x86-64-v4 -mprefer-vector-width=512 -ftree-vectorize  -mno-vzeroupper " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -march=x86-64-v4 -mprefer-vector-width=512 -ftree-vectorize -mno-vzeroupper " >> ~/.R/Makevars
R CMD INSTALL --preclean  --install-tests --use-LTO --no-test-load --data-compress=none --compress=none --built-timestamp=${SOURCE_DATE_EPOCH} --build  -l %{buildroot}-v4/usr/lib64/R/library .
echo "CFLAGS = $CFLAGS -ftree-vectorize " > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -ftree-vectorize " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -ftree-vectorize " >> ~/.R/Makevars
R CMD INSTALL --preclean  --use-LTO --install-tests --data-compress=none --compress=none --built-timestamp=${SOURCE_DATE_EPOCH} --build  -l %{buildroot}/usr/lib64/R/library .
%{__rm} -rf %{buildroot}%{_datadir}/R/library/R.css
%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export _R_CHECK_FORCE_SUGGESTS_=false
R CMD check --no-manual --no-examples --no-codoc . || :

/usr/bin/elf-move.py avx2 %{buildroot}-v3 %{buildroot} %{buildroot}/usr/share/clear/filemap/filemap-%{name}
/usr/bin/elf-move.py avx512 %{buildroot}-v4 %{buildroot} %{buildroot}/usr/share/clear/filemap/filemap-%{name}

%files
%defattr(-,root,root,-)
/usr/lib64/R/library/maxLik/CITATION
/usr/lib64/R/library/maxLik/DESCRIPTION
/usr/lib64/R/library/maxLik/INDEX
/usr/lib64/R/library/maxLik/Meta/Rd.rds
/usr/lib64/R/library/maxLik/Meta/features.rds
/usr/lib64/R/library/maxLik/Meta/hsearch.rds
/usr/lib64/R/library/maxLik/Meta/links.rds
/usr/lib64/R/library/maxLik/Meta/nsInfo.rds
/usr/lib64/R/library/maxLik/Meta/package.rds
/usr/lib64/R/library/maxLik/Meta/vignette.rds
/usr/lib64/R/library/maxLik/NAMESPACE
/usr/lib64/R/library/maxLik/NEWS
/usr/lib64/R/library/maxLik/R/maxLik
/usr/lib64/R/library/maxLik/R/maxLik.rdb
/usr/lib64/R/library/maxLik/R/maxLik.rdx
/usr/lib64/R/library/maxLik/doc/index.html
/usr/lib64/R/library/maxLik/doc/intro-to-maximum-likelihood.R
/usr/lib64/R/library/maxLik/doc/intro-to-maximum-likelihood.Rnw
/usr/lib64/R/library/maxLik/doc/intro-to-maximum-likelihood.pdf
/usr/lib64/R/library/maxLik/doc/stochastic-gradient-maxLik.R
/usr/lib64/R/library/maxLik/doc/stochastic-gradient-maxLik.Rnw
/usr/lib64/R/library/maxLik/doc/stochastic-gradient-maxLik.pdf
/usr/lib64/R/library/maxLik/doc/using-maxlik.R
/usr/lib64/R/library/maxLik/doc/using-maxlik.Rnw
/usr/lib64/R/library/maxLik/doc/using-maxlik.pdf
/usr/lib64/R/library/maxLik/help/AnIndex
/usr/lib64/R/library/maxLik/help/aliases.rds
/usr/lib64/R/library/maxLik/help/maxLik.rdb
/usr/lib64/R/library/maxLik/help/maxLik.rdx
/usr/lib64/R/library/maxLik/help/paths.rds
/usr/lib64/R/library/maxLik/html/00Index.html
/usr/lib64/R/library/maxLik/html/R.css
/usr/lib64/R/library/maxLik/tests/BFGSR.R
/usr/lib64/R/library/maxLik/tests/BFGSR.Rout.save
/usr/lib64/R/library/maxLik/tests/constraints.R
/usr/lib64/R/library/maxLik/tests/constraints.Rout.save
/usr/lib64/R/library/maxLik/tests/finalHessian.R
/usr/lib64/R/library/maxLik/tests/finalHessian.Rout.save
/usr/lib64/R/library/maxLik/tests/numericGradient.R
/usr/lib64/R/library/maxLik/tests/numericGradient.Rout.save
/usr/lib64/R/library/maxLik/tests/tinytest.R
/usr/lib64/R/library/maxLik/tinytest/test-basic.R
/usr/lib64/R/library/maxLik/tinytest/test-maxControl.R
/usr/lib64/R/library/maxLik/tinytest/test-maxSG.R
/usr/lib64/R/library/maxLik/tinytest/test-methods.R
/usr/lib64/R/library/maxLik/tinytest/test-optimizers.R
/usr/lib64/R/library/maxLik/tinytest/test-parameters.R
